- mfr/cli.py
- mfr_pdb/render-requirements.txt
- mfr_pdb/render.py
Purpose
=======
* Limit dirs/files searched to only directories with valid naming convention when calling <code>mfr install all<code>
* Closes https://github.com/CenterForOpenScience/modular-file-renderer/issues/122
Changes
=======
Ignores non-directories and non-matching directories when installing plugins
Side Effects
==========
Removes unnecessary render-requirements.txt from mfr_pdb
> Make CLI install modules matching 'mfr_[module]'

- mfr/ext/pdf/templates/pdfpage.mako
Purpose
=======
The pdf forward/back buttons scale to initial size of canvas on load and whenever the window/zoom is changed, but don't resize themselves when the pdf is first loaded into the canvas.
Changes
=======
Call <code>resizeCanvas()</code> immediately after the pdf is rendered.
Side Effects
==========
None
> Resize canvas on initial load

- mfr/ext/code_pygments/__init__.py
- mfr/ext/code_pygments/render.py
- mfr/ext/code_pygments/tests/test_code_pygments.py
Adds back support for `.md` files in `ext.code_pygments`. 
Fixes https://trello.com/c/2Rjygl8y/354-markdown-files-fail-to-render
> Default to TextLexer if default lexer cannot be found

- mfr/ext/ipynb/render-requirements.txt
Purpose
=======
Build fails due to recent update of IPython to 3.0
Changes
=======
Pin IPy to 2.1.0
Side Effects
=========
None
> Pin to old, working version of IPy

- mfr/ext/tabular/libs/panda_tools.py
- mfr/ext/tabular/tests/fixtures/test.csv
- mfr/ext/tabular/tests/test_panda_tools.py
- mfr/ext/tabular/utilities.py
The `strip_comments` helper was previously attempting to encode
(potentially) bytestrings to bytestrings, which caused rendering with
non-ascii characters to fail. This patch only decodes to bytes if
necessary, and updates the csv test fixture with a unicode character to
prevent future regressions.
@sloria @mfraezz: This fixes the problem I was running into on OSF, but open to a better solution if this one is not rad.
> Handle unicode characters in table files; add regression test.

- mfr/ext/docx/render.py
Purpose
=======
Display special characters that were being ignored.
Closes: https://github.com/CenterForOpenScience/osf.io/issues/1739
Changes
=======
Remove code that was originally used to fix a now unreproducible bug
Side Effects
=========
A UnicodeDecodeError may show up somewhere, somehow
> Display special characters

- mfr/core/utils.py
- mfr/settings.py
The warning messages in MFR are too abstract to users. 
Resolve https://github.com/CenterForOpenScience/osf.io/issues/3907
Move warning message into setting page and also change the text.
Change the warning message when dealing with non-supported file type
Old: `No renderer could be found for the file type requested.`
New: `Viewing of this file type is not currently supported. Please download the file to view.`
Change the warning message when dealing with non-exported file type
Old: `No exporter could be found for the file type requested.`
New: `Exporting of this file type is not currently supported.`
None
> [Feature Fix] Refine MRF warning message not supporting rendering and exporting

- mfr/server/app.py
I had to read the source code to figure out where the server was listening, and I thought this was a nice addition (and I've seen it done this way with quite a few server frameworks in the past).
Just a suggestion.
> Added output at startup about address and port

- mfr/extensions/tabular/templates/viewer.mako
Purpose
=======
Search was case-sensitive, this can be annoying to users
Changes
=======
Use case insensitive RE matching. This was chosen over `.toUpperCase()` for special unicode characters.
Side Effects
=========
None
> [Feature][Fix] Use case-insensitive search for tabular row filtering

- mfr/extensions/codepygments/static/css/default.css
- mfr/server/static/css/mfr.css
In Firefox, `word-wrap: break-word` will not break the line in pre-tag.  To test it, you can run the [link](http://jsfiddle.net/oc49Lv3y/1/) and compare the result of firefox with any other major browsers.
resolve [OSF-3532]
There are two possible solutions. One is to add new pre css and apply it to all browsers -- [Link](https://css-tricks.com/snippets/css/make-pre-text-wrap/). But it need to apply all the other browser. And also it requires to override a lot of css on bootstrap.
So I tried another method that is to add firefox specific css on mfr.css.
*  The tricks to target css on firefox  -- [Link](https://css-tricks.com/snippets/css/css-hacks-targeting-firefox/). Add code specific for Firefox
~~~
@-moz-document url-prefix() { 
.selector {
color:lime;
}
}
~~~
*  Use `white-space` and …
> [Feature Fix] Add wrap in pre on Firefox [OSF-3532]

- mfr/extensions/tabular/templates/viewer.mako
Purpose
=======
The compare function that sorts tabular data should but does not compare stringified numbers properly.
Changes
=======
* If values to be compared are numbers, parse them as such. Otherwise, use default string ordering.
Side Effects
==========
Columns populated with both strings and numbers still behave oddly, but it's no worse than before.
> Sort stringified numbers as numbers, not strings

- .travis.yml
- Dockerfile
- README.md
- docs/install.rst
- mfr/extensions/ipynb/render.py
- mfr/extensions/tabular/libs/__init__.py
- mfr/extensions/tabular/libs/panda_tools.py
- mfr/extensions/tabular/libs/stdlib_tools.py
- mfr/extensions/tabular/settings.py
- mfr/extensions/tabular/utilities.py
- requirements.txt
This PR removes deps on `IPython` and `rpy2` in favor of lighter-weight alternatives.
> [CR] remove some unneeded libraries

- mfr/extensions/pdf/static/web/viewer.js
The fullscreen/presentation mode button does not work in Safari. This PR fixes that by correcting the webkit fullscreen request name.
Changed `webkitRequestFullScreen`  to `webkitRequestFullscreen` ('s' in screen is not supposed to be capitalized).
None visible.
[https://openscience.atlassian.net/browse/OSF-7030](https://openscience.atlassian.net/browse/OSF-7030)
> Fix presentation mode not working with correct fullscreen request name

- mfr/server/static/js/mfr.js
Same as #276 , now as a hotfix.
.load is changed in jQuery 3. Use .on('load', ...) instead.
https://openscience.atlassian.net/browse/OSF-8638
This is backwards-compatible with older jQuery versions.
> [OSF-8638] Fix jquery 3 compatibility

- dev-requirements.txt
No ticket or ticket to be created
This is a follow up PR for https://github.com/CenterForOpenScience/modular-file-renderer/pull/312 and https://github.com/CenterForOpenScience/waterbutler/pull/321. Instead of deleting it, I updated `aiohttpretty` and commented it out with a note in case we need it for tests in the future.
As stated in **Purpose**
No
No. This is a backend change for local development and travis only.
No. Make sure that travis passes.
> [No Ticket]  Update and disable aiohttpretty

- mfr/extensions/image/templates/viewer.mako
https://openscience.atlassian.net/browse/SVCS-571
Fix the issue that IE does not resize image to fit window size. 
Explicitly set `"max-width": "100%"` and `"height": "auto"`.
No
Test small, medium and large files on IE for this fix and on other supported browsers to make sure that nothing breaks.
No
> [SVCS-571] Fix Image Hi-Res and Zoom for IE

- mfr/extensions/pdb/settings.py
- mfr/extensions/tabular/settings.py
- mfr/extensions/unoconv/settings.py
- mfr/server/settings.py
- mfr/settings.py
N/A
Allow JSON objects and arrays to be passed into as environment variable settings, needed for Storage Internationalization project.
Adds `get_object` to the base Settings class, **in the correct alphabetical order**.
None
N/A
Can now use JSON in environment variables, e.g.
```bash
export SERVER_CONFIG_CACHE_PROVIDER_SETTINGS='{
"bucket": "cos-osf-stage-files-ca-1-mfr"
}'
```
> [No Ticket] Add get_object to interpret JSON settings

- mfr/server/handlers/export.py
https://openscience.atlassian.net/browse/SVCS-678
When MFR receives an export request where the input and output formats are the same, it should simply return the original file unmodified... unless there's another reason to export the file (i.e. image scaling).
A no-op is a simple operation to support, why not do it?
A PR to support
Devs will test this. Dev, please add a list of affected and unaffected file types.
- this affects all file types. Any file type may now be exported. The extension of the file must match exactly the extension of the export, or we respond saying we cant export it. (i.e .jpg and .100\*100.jpg are not the same, and the 100\*100.jpg will trigger a actual file conversion)
Build an MFR export url requesting to export a file of type foo as type foo. This should start …
> [SVCS-678] Add noop for export (Functionality Only)

- mfr/extensions/pdf/render.py
No Ticket
The issue was discovered during CR and testing https://github.com/CenterForOpenScience/modular-file-renderer/pull/330
TIF/TIFF is both rendered and exported by the PDF renderer and exporter.
However, the renderer only allows .tif and .tiff to be exported but
accidentally leaves .TIF and .TIFF behind. They end up being rendered
directly as PDF which fails.
`self.metadata.ext.l` -->> `self.metadata.ext.lower()`
No
Both https://staging.osf.io/9ra6c/ and https://staging.osf.io/vprtu/ works on staging.
No
> [No Ticket] Fix case-sensitive check for TIFF in PDF renderer

- mfr/core/provider.py
- mfr/core/utils.py
- mfr/providers/osf/provider.py
- mfr/providers/osf/settings.py
- mfr/server/handlers/core.py
https://openscience.atlassian.net/browse/SVCS-674
Help OSF get more accurate MFR render/export statistics.
When MFR requests metadata from WB, it should set a header identifying itself and indicating the type of MFR action being performed.  WB will relay that information to the OSF in the authorization request.  This will allow the OSF to distinguish contributor vs. non-contributor views and also avoid missing views due to MFR caching.
None expected.  Will do nothing until SVCS-831 is merged into WB.
None.
None.
> [SVCS-674] signal MFR action in WB metadata request

- setup.cfg
There are some python files in node_modeles, and these packages tests
shouldn't run when we run MFR tests.
> Ignore node_modules when running pytest

- mfr/providers/osf/provider.py
No ticket
Tidies up the operation of a little bit of code.
The OSF provider was passing a header with an empty value, this change
means the if the header is empty, then the header isn't sent at all.
This technically is a small optimization as well, it removes a few
instructions that would get called inside aiohttp. if this header was
here. (This is probably insignificant, however.)
OSF gets no header in this situation now
> Dont pass empty header

- mfr/extensions/pdf/templates/viewer.mako
https://openscience.atlassian.net/browse/SVCS-880
The toolbar has a minimum size, so on mobile, the hypothesis bar overlaps with things on the pdf toolbar. This moves the hypothesis toolbar down by the height of the pdfjs toolbar so it doesn't obscure anything.
The toolbar is moved down by 32 pixels, which it is not if using the hypothesis extension on a non-osf pdf.
> Fix hypothesis overlapping toolbar

- mfr/extensions/jsc3d/export.py
- mfr/extensions/jsc3d/settings.py
- mfr/extensions/tabular/settings.py
- mfr/extensions/tabular/utilities.py
- mfr/extensions/unoconv/export.py
[SVCS-683](https://openscience.atlassian.net/browse/SVCS-683) Add timeouts for subprocess calls
Make subprocess time out instead of hanging indefinitely.
May make files that are particularly large time out if they take too long.
Adds a couple of ENV vars to configure the timeout if desired. Default set to 10s.
> [][SVCS-683] Add timeouts for subprocess calls

- mfr/extensions/image/static/js/jquery.zoom.js
https://openscience.atlassian.net/browse/SVCS-918
cc and h/t @Johnetordoff for discovering this
Fix the issue where zooming does not work properly for `.GIF`s with transparent background. Here is the [example](https://staging.osf.io/3ca45/) on `staging` OSF.  This bug only affects non-exported types: `.GIF` and `.ICO`. For exported ones, the export type `.JPEG` does not have transparency so the background is set to white by default.
- The fix simply set a white background when the zoom image's style class is generated on the page.
No
Test that image rendering and zooming works as expected.
* `.GIF` with transparent background: https://staging.osf.io/3ca45/
* `.GIF` with non-transparent background: https://staging.osf.io/3r9m7/
* Plus a few other static images
No
> [HotFix] [SVCS-918] Use White Background For Zoomed Images

- mfr/extensions/pdf/render.py
- mfr/extensions/pdf/templates/viewer.mako
- mfr/server/static/js/mfr.child.hypothesis.js
- mfr/settings.py
https://openscience.atlassian.net/browse/ENG-44
To add GA tracking to MFR to track when users click open the Hypothesis panel.
- In `mfr/extensions/pdf/templates/viewer.mako`, we add GA tracking imports.
- In `mfr/server/static/js/mfr.child.hypothesis.js`, we set `window.hypothesisConfig` to use the `onLayoutChange()` callback provided by hypothesis to watch for opening of annotation panel.
- Add GA tracking ID to settings and use that in renderer.
None
Check to make sure the event is only tracked when users open the panel for the first time on that page. Page refresh counts as a new page. User is counted by browser, not OSF User. So if the same OSFUser opens two browser and opens the panel in both, it counts as two events.
Add GOOGLE_ANALYTICS_TRACKING_ID for to staging/prod settings.
> [ENG-44] Add google analytics tracking for when hypothesis side panel is opened

- Dockerfile
No ticket.
* Update installed LO version to v6.1.5, since the archive with the old version is no longer available.
* Pin base docker image to debian stretch, since jessie is being removed from the mirrors. Update libpng dep to match.
* Make gpg support more reliable by adding fallback servers and disabling ipv6 lookup
* Style fixes: indentation, explicitly install/uninstall gpg dependency
Hopefully none!
Deployment environments need configuration updated before testing.  Expected behavior is: no change in rendering.
Need to update helm charts to look for unoconv's LO python in `/opt/libreoffice6.1/` instead of `/opt/libreoffice6.0`.
> [CR][No ticket] Dockerfile updates (New LO version, other fixes)

- Dockerfile
https://openscience.atlassian.net/browse/ENG-379
Update base image to Debian Buster to allow installing LibreOffice from apt-get.
Install libreoffice via apt-get instead of downloading `.deb` file from LO's archives.
None expected.  This can be tested/released independently of the [`docker-library` fix](https://github.com/CenterForOpenScience/docker-library/pull/51).
Dev QA only.
Nope.
> [CR][ENG-379] update Dockerfile to be based on debian buster

- requirements.txt
- tasks.py
None.
The python module `certifi` was pinned to a very old version to work around issues with Rackspace. Not only is it no longer relevant, it can no longer successfully validate TLS certs.
* Update `certifi` pin to latest release
* Remove `monkey_patch`
None expected
> [Hotfix] Remove old pin to certifi

- Dockerfile
- dev-requirements.txt
- mfr/server/app.py
- mfr/server/handlers/core.py
- requirements.txt
https://openscience.atlassian.net/browse/ENG-7595
Update Dockerfile to be based off py3.13. May need to update non-python deps, but do not need to update python code. Not necessary to run at the end.
update MFR Dockerfile and some python packeges to make it possible to create mfr image and containers afterward without errors (it looks like another packages dev-group and related code for MFR will be needed to updated as it was for WB)
previosly
now 
for 3.13 testing purposes change in osf `docker-compose.yml`
```
mfr_requirements_vol_3_13:
external: false
mfr_requirements_local_bin_vol_3_13:
external: false
```
```
mfr_requirements:
image: mfr3.13_v1:develop
command:
- /bin/bash
- -c
- invoke install --develop &&
(python -m compileall /usr/local/lib/python3.13 || true) &&
rm -Rf …
```
> [ENG-7595] 3.2.1 BE: MFR Update Dockerfile to py3.13

- requirements.txt
[ENG-7600]
- Bump dependency groups ext-code and ext-docs
- Bump chardet
- Bump Pygments
- Bump pydocs
- Bump reportlab
- Bump docutils
- Bump markdown
[ENG-7600]: https://openscience.atlassian.net/browse/ENG-7600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-7600] Bump dependencies for ext-code and ext-doc

- mfr/core/remote_logging.py
- mfr/providers/osf/provider.py
- requirements.txt
- setup.cfg
https://openscience.atlassian.net/browse/ENG-7752
Update dependencies in dep-group “test”.
The dep-group tickets are about updating a batch of dependencies at a time. In the MFR requirements DB, column C is "group". I've tried to group similar dependencies together. When you take on a dep-group ticket, you're trying to upgrade all the tickets in that group to their latest version.
It  may turn out that some of the modules in one group break or require changes for a module in another group. That's okay; we'll deal with those on a case-by-case basis. If we have to leave something out or drag something in it, that's fine.  We can also break things out into smaller dep-groups with new tickets if that makes sense.
Update code to make it possible to run the tests for python3.13 
make the PR …
> [Eng-7752] tests deps upgrade

- mfr/tasks/__init__.py
- mfr/tasks/app.py
- mfr/tasks/core.py
- mfr/tasks/exceptions.py
- mfr/tasks/render.py
- mfr/tasks/settings.py
- poetry.lock
- pyproject.toml
- tasks.py
> [ENG-7608] 3.5.4 BE: Add mfr-worker entrypoint

- Dockerfile
> [ENG-8355] | MFR Update libreoffice version in dockerfile

- docs/conf.py
- docs/extensions.rst
- docs/install.rst
- readthedocs.yml
https://openscience.atlassian.net/browse/ENG-8427?atlOrigin=eyJpIjoiZmY2MjBiMWZlMjgyNDA0Y2I5N2RkNmZlNGU0MzYwM2UiLCJwIjoiaiJ9
> [ENG-8427] Update docs
